### ISSUE TITLE
Direct URLs for search and settings

### ISSUE THREAD

**Issue by dayofthedave** [BenoitBellegarde/UltimateTab#19]
Nice app! Is there a way to link directly to a search results page? Something like https://ultimate-tab.com/search?q=hotel%20california%20eagles&type=chords would be really handy for sharing links to multiple charts.

**Comment by dayofthedave** [comment]
Just shared my instance with a bandmate, and he asked if stuff like light/dark mode and transposition could be set via query parameters too.

**Comment by BenoitBellegarde** [comment]
Hi @dayofthedave, thank you for your interest in the project ! 
Currently, it’s not possible, but it’s a feature I could add without much difficulty. At the moment, I don’t have much time to work on the project, but I’m gathering feedback from several people interested in the project to see if I should start hosting the site again and make it evolve. Feel free to give me feedback here 🙂 : https://github.com/BenoitBellegarde/UltimateTab/issues/18#issuecomment-2216635075

**Comment by AstudilloMarillo** [comment]
I would also really like this feature. It'd make it possible to quickly search songs using something like Flow Launcher or PowerToys Run.

**Comment by BenoitBellegarde** [comment]
Hi @dayofthedave @AstudilloMarillo,
I just added URL parameters to filter the search, so you can now filter using these 3 parameters via the URL:

"q": Name of the artist/song to search for
"type": Chords/Tab/Bass/Ukulele/All
"page": Page number
The URL is automatically updated as you navigate the site, so you can copy and paste the URL at any time to share your search results.

@dayofthedave I changed it to set the light mode as the default, but I don't think I will implement managing this parameter via the URL since this setting is saved in local storage in the browser. You only need to change it once, and it will be saved for all future sessions on the site.
Regarding transposition, at the moment, it's a bit too complicated to pass this parameter via the URL with the way I’ve implemented transposition. I would need to rework this part to accommodate that integration. I’ll keep you updated as soon as I have time to do this.

Have a great day folks! :)

**Comment by AstudilloMarillo** [comment]
> I just added URL parameters to filter the search, so you can now filter using these 3 parameters via the URL:
> 
> "q": Name of the artist/song to search for "type": Chords/Tab/Bass/Ukulele/All "page": Page number

This is above and beyond! Immediately made Flow Launcher shortcuts for each type option. Thanks a lot.

**Comment by dayofthedave** [comment]
Thank you so much!
