### ISSUE TITLE
"TypeError: getCheckboxProps is not a function" in  Search

### ISSUE THREAD

**Issue by xpufx** [BenoitBellegarde/UltimateTab#37]
While trying to build a docker image I tried to build the project with both alpine based nodejs versions (21/18) and the latest official nodejs image and I am getting the same error in every instance. Using npm vs yarn does not make a difference.

![image](https://github.com/user-attachments/assets/3009efb1-54e3-45b0-bf72-66316362c7c6)

I don't know if this is something to be fixed or it's a nodejs/yarn/os issue. Can you share the environment the current site runs on. It might actually be nice to show some sort of a git tag/version at the bottom of the web interface too.

**Comment by BenoitBellegarde** [comment]
Hi @xpufx, the site is currently running on NodeJS v18.14.2 and npm 9.5.0. You should be able to build the project with these versions. I remember having compatibility issues when building with NodeJS v20.x, which is why I’m using such an old version. Unfortunately, I don’t recall which dependencies were causing these issues...

I hope this helps!

**Comment by BenoitBellegarde** [comment]
Hi @xpufx , someone had the same issue as you recently and submitted a pull request with a fix. You shouldn't have any more problems now.

https://github.com/BenoitBellegarde/UltimateTab/issues/42
